export const products = [
  {
    name: "Marshall Major III",
    category: "headphone",
    brand: "marshall",
    price: 243.7,
    colors: ["black", "white"],
    slug: "marshall-major-iii",
    images: [
      "/products/marshall-major-iii-bt-black-01.webp",
      "/products/jbl-t450.png",
      "/products/marshall-minor-ii.webp",
    ],
  },
  {
    name: "JBL T450",
    category: "headphone",
    brand: "jbl",
    price: 263.46,
    colors: ["black"],
    slug: "jbl-t450",
    images: [
      "/products/jbl-t450.png",
      "/products/marshall-major-iii-bt-black-01.webp",
      "/products/marshall-minor-ii.webp",
    ],
  },
  {
    name: "Marshall Minor II",
    category: "earphone",
    brand: "marshall",
    price: 150,
    colors: ["black"],
    slug: "marshall-minor-ii",
    images: [
      "/products/marshall-minor-ii.webp",
      "/products/jbl-t450.png",
      "/products/marshall-major-iii-bt-black-01.webp",
    ],
  },
  {
    name: "Marshall Major III",
    category: "headphone",
    brand: "marshall",
    price: 243.7,
    colors: ["black", "white"],
    slug: "marshall-major-iii",
    images: [
      "/products/marshall-major-iii-bt-black-01.webp",
      "/products/jbl-t450.png",
      "/products/marshall-minor-ii.webp",
    ],
  },
  {
    name: "JBL T450",
    category: "headphone",
    brand: "jbl",
    price: 263.46,
    colors: ["black"],
    slug: "jbl-t450",
    images: [
      "/products/jbl-t450.png",
      "/products/marshall-major-iii-bt-black-01.webp",
      "/products/marshall-minor-ii.webp",
    ],
  },
  {
    name: "Marshall Minor II",
    category: "earphone",
    brand: "marshall",
    price: 150,
    colors: ["black"],
    slug: "marshall-minor-ii",
    images: [
      "/products/marshall-minor-ii.webp",
      "/products/jbl-t450.png",
      "/products/marshall-major-iii-bt-black-01.webp",
    ],
  },
  {
    name: "Marshall Major III",
    category: "headphone",
    brand: "marshall",
    price: 243.7,
    colors: ["black", "white"],
    slug: "marshall-major-iii",
    images: [
      "/products/marshall-major-iii-bt-black-01.webp",
      "/products/jbl-t450.png",
      "/products/marshall-minor-ii.webp",
    ],
  },
  {
    name: "JBL T450",
    category: "headphone",
    brand: "jbl",
    price: 263.46,
    colors: ["black"],
    slug: "jbl-t450",
    images: [
      "/products/jbl-t450.png",
      "/products/marshall-major-iii-bt-black-01.webp",
      "/products/marshall-minor-ii.webp",
    ],
  },
  {
    name: "Marshall Minor II",
    category: "earphone",
    brand: "marshall",
    price: 150,
    colors: ["black"],
    slug: "marshall-minor-ii",
    images: [
      "/products/marshall-minor-ii.webp",
      "/products/jbl-t450.png",
      "/products/marshall-major-iii-bt-black-01.webp",
    ],
  },
  {
    name: "Marshall Major III",
    category: "headphone",
    brand: "marshall",
    price: 243.7,
    colors: ["black", "white"],
    slug: "marshall-major-iii",
    images: [
      "/products/marshall-major-iii-bt-black-01.webp",
      "/products/jbl-t450.png",
      "/products/marshall-minor-ii.webp",
    ],
  },
  {
    name: "JBL T450",
    category: "headphone",
    brand: "jbl",
    price: 263.46,
    colors: ["black"],
    slug: "jbl-t450",
    images: [
      "/products/jbl-t450.png",
      "/products/marshall-major-iii-bt-black-01.webp",
      "/products/marshall-minor-ii.webp",
    ],
  },
  {
    name: "Marshall Minor II",
    category: "earphone",
    brand: "marshall",
    price: 150,
    colors: ["black"],
    slug: "marshall-minor-ii",
    images: [
      "/products/marshall-minor-ii.webp",
      "/products/jbl-t450.png",
      "/products/marshall-major-iii-bt-black-01.webp",
    ],
  },
  {
    name: "Marshall Major III",
    category: "headphone",
    brand: "marshall",
    price: 243.7,
    colors: ["black", "white"],
    slug: "marshall-major-iii",
    images: [
      "/products/marshall-major-iii-bt-black-01.webp",
      "/products/jbl-t450.png",
      "/products/marshall-minor-ii.webp",
    ],
  },
  {
    name: "JBL T450",
    category: "headphone",
    brand: "jbl",
    price: 263.46,
    colors: ["black"],
    slug: "jbl-t450",
    images: [
      "/products/jbl-t450.png",
      "/products/marshall-major-iii-bt-black-01.webp",
      "/products/marshall-minor-ii.webp",
    ],
  },
  {
    name: "Marshall Minor II",
    category: "earphone",
    brand: "marshall",
    price: 150,
    colors: ["black"],
    slug: "marshall-minor-ii",
    images: [
      "/products/marshall-minor-ii.webp",
      "/products/jbl-t450.png",
      "/products/marshall-major-iii-bt-black-01.webp",
    ],
  },
  {
    name: "Marshall Major III",
    category: "headphone",
    brand: "marshall",
    price: 243.7,
    colors: ["black", "white"],
    slug: "marshall-major-iii",
    images: [
      "/products/marshall-major-iii-bt-black-01.webp",
      "/products/jbl-t450.png",
      "/products/marshall-minor-ii.webp",
    ],
  },
  {
    name: "JBL T450",
    category: "headphone",
    brand: "jbl",
    price: 263.46,
    colors: ["black"],
    slug: "jbl-t450",
    images: [
      "/products/jbl-t450.png",
      "/products/marshall-major-iii-bt-black-01.webp",
      "/products/marshall-minor-ii.webp",
    ],
  },
  {
    name: "Marshall Minor II",
    category: "earphone",
    brand: "marshall",
    price: 150,
    colors: ["black"],
    slug: "marshall-minor-ii",
    images: [
      "/products/marshall-minor-ii.webp",
      "/products/jbl-t450.png",
      "/products/marshall-major-iii-bt-black-01.webp",
    ],
  },
];

export const fullProducts = [
  {
    name: "Marshall Major IV",
    category: "headphone",
    brand: "marshall",
    price: 243.7,
    colors: ["black", "brown"],
    slug: "marshall-major-iv",
    images: [
      "/products/marshall-major-iv-black-01.png",
      "/products/marshall-major-iv-black-02.png",
      "/products/marshall-major-iv-black-03.png",
      "/products/marshall-major-iv-brown-01.webp",
      "/products/marshall-major-iv-brown-02.webp",
      "/products/marshall-major-iv-brown-03.webp",
    ],
    specifications: {
      collapsible: "yes",
      "headphone type": "on-ear",
      weight: "165g",
      "water resistence": "no",
    },
    description:
      "<p>Meet Major IV, the iconic headphones from Marshall with 80+ solid hours of wireless playtime, wireless charging and a new, improved ergonomic design. With more than three full days of power, you can stop worrying about your headphones dying on you when you need them. Custom-tuned dynamic drivers deliver roaring bass, smooth mids and brilliant treble for a rich, unrivalled sound that you'll never want to turn off.</p><h3>SIGNATURE SOUND</h3><p>Major IV delivers the signature Marshall sound that you've come to expect. Over 55 years of knowledge is packed into Major IV for an explosive sound. Custom-tuned dynamic drivers deliver roaring bass, smooth mids and brilliant treble for a rich, unrivalled sound that you'll never want to turn off.</p><h3>80+ HOURS OF WIRELESS PLAYTIME</h3><p>Major IV delivers 80+ solid hours of wireless playtime with quick-charge capability - only 15 minutes of charging will give you 15 hours of listening. These are headphones truly built for the long haul.</p><h3>WIRELESS CHARGING</h3><p>Major IV can be charged wirelessly, so it's now easier than ever to charge and go. You can rest your headphones neatly on a charging pad, and matte silicone piping on the ear cap ensures it won't move around. Spend less time looking for your charger in a mess of wires and more time listening to your music.</p><p>You will receive a USB-C charging cable in the box. Wireless charging pad is not included.</p><h3>IMPROVED ERGONOMIC DESIGN</h3><p>Major IV's new, improved ergonomic design means that when you're deep diving into your music, the tenth hour is as comfortable as the first. Major IV's ear cushions are softer to the touch and more faithfully fit the shape of your ear.</p><h3>MULTI-DIRECTIONAL CONTROL KNOB</h3><p>With the multi-directional control knob you can play, pause, skip and adjust the volume of your device, as well as power your headphones on or off. Phone functionality is also included so you can answer, reject or end a call with a few simple clicks.</p><h3>SHARE YOUR MUSIC</h3><p>As well as allowing you to plug in and play when you're low on power, Major IV's 3.5 mm socket also allows a friend to enjoy your music. Sharing music with friends is simple and speedy.</p><h3>ICONIC MARSHALL DESIGN</h3><p>Major IV combines enhanced usability with classic Marshall elements for a design that is both iconic and innovative. The new fold clip means that Major IV folds away into an even more compact size, and the ear caps are protected from too much wear and tear. It features the tactile and efficient control knob, textured black vinyl and Marshall script, as well as the rugged durability that's necessary for the anarchy of everyday life.<p>",
  },
  {
    name: "JBL T450",
    category: "headphone",
    brand: "jbl",
    price: 263.46,
    colors: ["black"],
    slug: "jbl-t450",
    images: [
      "/products/jbl-t450.png",
      "/products/marshall-major-iii-bt-black-01.webp",
      "/products/marshall-minor-ii.webp",
    ],
    specifications: {
      collapsible: "yes",
      "headphone type": "on-ear",
      weight: "165g",
      "water resistence": "no",
    },
    description:
      "<p>Meet Major IV, the iconic headphones from Marshall with 80+ solid hours of wireless playtime, wireless charging and a new, improved ergonomic design. With more than three full days of power, you can stop worrying about your headphones dying on you when you need them. Custom-tuned dynamic drivers deliver roaring bass, smooth mids and brilliant treble for a rich, unrivalled sound that you'll never want to turn off.</p><h3>SIGNATURE SOUND</h3><p>Major IV delivers the signature Marshall sound that you've come to expect. Over 55 years of knowledge is packed into Major IV for an explosive sound. Custom-tuned dynamic drivers deliver roaring bass, smooth mids and brilliant treble for a rich, unrivalled sound that you'll never want to turn off.</p><h3>80+ HOURS OF WIRELESS PLAYTIME</h3><p>Major IV delivers 80+ solid hours of wireless playtime with quick-charge capability - only 15 minutes of charging will give you 15 hours of listening. These are headphones truly built for the long haul.</p><h3>WIRELESS CHARGING</h3><p>Major IV can be charged wirelessly, so it's now easier than ever to charge and go. You can rest your headphones neatly on a charging pad, and matte silicone piping on the ear cap ensures it won't move around. Spend less time looking for your charger in a mess of wires and more time listening to your music.</p><p>You will receive a USB-C charging cable in the box. Wireless charging pad is not included.</p><h3>IMPROVED ERGONOMIC DESIGN</h3><p>Major IV's new, improved ergonomic design means that when you're deep diving into your music, the tenth hour is as comfortable as the first. Major IV's ear cushions are softer to the touch and more faithfully fit the shape of your ear.</p><h3>MULTI-DIRECTIONAL CONTROL KNOB</h3><p>With the multi-directional control knob you can play, pause, skip and adjust the volume of your device, as well as power your headphones on or off. Phone functionality is also included so you can answer, reject or end a call with a few simple clicks.</p><h3>SHARE YOUR MUSIC</h3><p>As well as allowing you to plug in and play when you're low on power, Major IV's 3.5 mm socket also allows a friend to enjoy your music. Sharing music with friends is simple and speedy.</p><h3>ICONIC MARSHALL DESIGN</h3><p>Major IV combines enhanced usability with classic Marshall elements for a design that is both iconic and innovative. The new fold clip means that Major IV folds away into an even more compact size, and the ear caps are protected from too much wear and tear. It features the tactile and efficient control knob, textured black vinyl and Marshall script, as well as the rugged durability that's necessary for the anarchy of everyday life.<p>",
  },
  {
    name: "Marshall Minor II",
    category: "earphone",
    brand: "marshall",
    price: 150,
    colors: ["black"],
    slug: "marshall-minor-ii",
    images: [
      "/products/marshall-minor-ii.webp",
      "/products/jbl-t450.png",
      "/products/marshall-major-iii-bt-black-01.webp",
    ],
    specifications: {
      collapsible: "yes",
      "headphone type": "on-ear",
      weight: "165g",
      "water resistence": "no",
    },
    description:
      "<p>Meet Major IV, the iconic headphones from Marshall with 80+ solid hours of wireless playtime, wireless charging and a new, improved ergonomic design. With more than three full days of power, you can stop worrying about your headphones dying on you when you need them. Custom-tuned dynamic drivers deliver roaring bass, smooth mids and brilliant treble for a rich, unrivalled sound that you'll never want to turn off.</p><h3>SIGNATURE SOUND</h3><p>Major IV delivers the signature Marshall sound that you've come to expect. Over 55 years of knowledge is packed into Major IV for an explosive sound. Custom-tuned dynamic drivers deliver roaring bass, smooth mids and brilliant treble for a rich, unrivalled sound that you'll never want to turn off.</p><h3>80+ HOURS OF WIRELESS PLAYTIME</h3><p>Major IV delivers 80+ solid hours of wireless playtime with quick-charge capability - only 15 minutes of charging will give you 15 hours of listening. These are headphones truly built for the long haul.</p><h3>WIRELESS CHARGING</h3><p>Major IV can be charged wirelessly, so it's now easier than ever to charge and go. You can rest your headphones neatly on a charging pad, and matte silicone piping on the ear cap ensures it won't move around. Spend less time looking for your charger in a mess of wires and more time listening to your music.</p><p>You will receive a USB-C charging cable in the box. Wireless charging pad is not included.</p><h3>IMPROVED ERGONOMIC DESIGN</h3><p>Major IV's new, improved ergonomic design means that when you're deep diving into your music, the tenth hour is as comfortable as the first. Major IV's ear cushions are softer to the touch and more faithfully fit the shape of your ear.</p><h3>MULTI-DIRECTIONAL CONTROL KNOB</h3><p>With the multi-directional control knob you can play, pause, skip and adjust the volume of your device, as well as power your headphones on or off. Phone functionality is also included so you can answer, reject or end a call with a few simple clicks.</p><h3>SHARE YOUR MUSIC</h3><p>As well as allowing you to plug in and play when you're low on power, Major IV's 3.5 mm socket also allows a friend to enjoy your music. Sharing music with friends is simple and speedy.</p><h3>ICONIC MARSHALL DESIGN</h3><p>Major IV combines enhanced usability with classic Marshall elements for a design that is both iconic and innovative. The new fold clip means that Major IV folds away into an even more compact size, and the ear caps are protected from too much wear and tear. It features the tactile and efficient control knob, textured black vinyl and Marshall script, as well as the rugged durability that's necessary for the anarchy of everyday life.<p>",
  },
];
